leave=0
while leaveprogram != "q":
    improt random
    print("This is a dice rolling program")
    print("press r to roll")
    input()
    number=random.randint(1,6)
    if number==1:
        print("[-------------]")
        print("[             ]")
        print("[      ●      ]")
        print("[             ]")
        print("[-------------]")
        print()
        print("Type 'q' to quit")
        leaveprogram=input()
    if number==2:
        print("[-------------]")
        print("[             ]")
        print("[   ●      ●  ]")
        print("[             ]")
        print("[-------------]")
        print()
        print("Type 'q' to quit")
        leaveprogram=input()
    if number==3:
        print("[-------------]")
        print("[   ●     ●   ]")
        print("[             ]")
        print("[      ●      ]")
        print("[-------------]")
        print()
        print("Type 'q' to quit")
        leaveprogram=input()
    if number==4:
        print("[-------------]")
        print("[   ●     ●   ]")
        print("[             ]")
        print("[   ●     ●   ]")
        print("[-------------]")
        print()
        print("Type 'q' to quit")
        leaveprogram=input()
    if number==5:
        print("[-------------]")
        print("[   ●     ●   ]")
        print("[      ●      ]")
        print("[   ●     ●   ]")
        print("[-------------]")
        print()
        print("Type 'q' to quit")
        leaveprogram=input()
    if number==6:
        print("[-------------]")
        print("[   ●     ●   ]")
        print("[   ●     ●   ]")
        print("[   ●     ●   ]")
        print("[-------------]")
        print()
        print("Type 'q' to quit")
        leaveprogram=input()