percentage = [48, 50, 2]
sports = ["calisthenics", "calisthenics", "cycling", "gymnastics"]
sports.append("bungi jumping")
print(sports)
sports.insert(1, "bungi jumping")
print(sports)
sports.remove("gymnastics")
print(sports)
sports.pop()
print(sports)
sports.extend(percentage)
print(sports)
sports.clear()
print(sports)
print(sports.count("calisthenics"))
sports.sort()
print(sports)
sports.reverse()
print(sports)
sports2 = sports.copy()